### PR TITLE
update README

### PR DESCRIPTION
**Pull request by DivineDominion**
Should now reflect the changes you made.

Also, the functionality is severely limited compared to Dom's script where the app id would be printed. Would love to have some more info about this move.

### CODE REVIEW

**Comment by overheadhunter** [comment]
haha yeah right, I didn't update the readme :D when we made the changes this year, we dropped all the features we previously implemented. before one was even able to [include/exclude apps onto the bill](https://github.com/overheadhunter/CreateAppStoreBill/commit/38388c54b25c9f7b0434500dc79e894a75c9456f#diff-c27d91463993afd35a15cb7fba55615dL12). but eventually we didn't need that any longer, so we removed app ids completely :D

**Comment by DivineDominion** [comment]
How's that? I thought you'd have to break down sales per product. You sure this isn't the case?

**Comment by overheadhunter** [comment]
Apple changed the raw data. The app id is no longer available in the current .csv file..

**Comment by DivineDominion** [comment]
Dang. Does the loss of per-item sales info not cause any problems? -- Then again [FastSpring](https://docs.fastspring.com/getting-started-with-fastspring/currencies-conversions-and-taxes/about-vat-and-sales-tax) has an example invoice where 1 item for the payment suffices and doesn't need to be broken down to product sales numbers.

**Pull request merged**
